# General Settings
favicon: "/assets/images/logo/favicon.png"
name: "Dr. Moosbrugger"

# Contact info
contact_settings:
  email: "marcel@marcelmoos.com"

# Google analytics code
google_analytics:
  enable: true 
  key: "G-1FW0SSZT8G"

# Socail urls
social_settings:
  instagram_url: 'https://www.instagram.com/mmsbrggr'
  github_url: 'https://github.com/mmsbrggr'
  linkedin_url: 'https://www.linkedin.com/in/marcelmoos'
  substack_url: 'https://substack.com/@marcelmoos'
