# General Settings
favicon: "/assets/images/logo/favicon.png"
name: "Dr. Moosbrugger"

# Contact info
contact_settings:
  email: "hello@dexfolio.net.us"

# Google analytics code
google_analytics:
  enable: false
  key: "UA-664136761-1" # UA-664136761-1

# Socail urls
social_settings:
  instagram_url: 'https://www.instagram.com/mmsbrggr'
  github_url: 'https://github.com/mmsbrggr'
  linkedin_url: 'https://www.linkedin.com/in/marcelmoos'
  substack_url: 'https://substack.com/@marcelmoos'
