title: "Dr. Marcel Moosbrugger" 
description: "Dr. Marcel Moosbrugger - Keynotes & Talks - Science Communication - Research"

# Footer info
footer_settings:
  copyright_text: "All Rights Reserved by"
  legal_notice: "LEGAL NOTICE"
  data_privacy: "DATA PRIVACY"

cookie_banner:
  neccessary:
    name: "Necessary"
    description: "These cookies are necessary for the website to function properly and cannot be switched off. They help with things like logging in and setting your privacy preferences."
  analytical:
    name: "Analytical"
    description: "These cookies help us improve the site by tracking which pages are most popular and how visitors move around the site."
  banner:
    description: "We use cookies on our site to enhance your user experience, provide personalized content, and analyze our traffic. <a href='/data-privacy' target='_blank'>Cookie Policy.</a>"
    acceptAllButtonText: "Accept all"
    acceptAllButtonAccessibleLabel: "Accept all cookies"
    rejectNonEssentialButtonText: "Reject non-essential"
    rejectNonEssentialButtonAccessibleLabel: "Reject non-essential"
    preferencesButtonText: "Preferences"
    preferencesButtonAccessibleLabel: "Toggle preferences"
  
  preferences: 
    title: "Customize your cookie preferences"
    description: "We respect your right to privacy. You can choose not to allow some types of cookies. Your cookie preferences will apply across our website."
    onText: "On"
    offText: "Off"
