title: "Dr. Marcel Moosbrugger" 
description: "Dr. Marcel Moosbrugger - Keynotes & Talks - Science Communication - Research"

# Footer info
footer_settings:
  copyright_text: "All Rights Reserved by"
  legal_notice: "LEGAL NOTICE"

